# -*- coding: utf-8 -*-
"""빅데티어_교촌치킨.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZacIhJ_VdGGLRbFcv3geoRxR_Us_6XH
"""

pip install beautifulsoup4

from bs4 import BeautifulSoup

import urllib.request

import datetime

def get_request_url(url):
    req = urllib.request.Request(url)
    try:
        response = urllib.request.urlopen(req)
        if response.getcode() == 200 :
            return response.read().decode('utf-8')
    except Exception as err:
        return None

results =[]

for sido1 in range(1,18):
  for sido2 in range(1, 45):
    print(sido1,",",sido2, end=" / ")
    url = 'http://www.kyochon.com/shop/domestic.asp?sido1='+str(sido1)+'&sido2='+str(sido2)+'&txtsearch='
    html = get_request_url(url)
    print(url)
    if html == None :
      break;
    bs = BeautifulSoup(html, 'html.parser')
    tag_div = bs.find('div', attrs={'class': 'shopSchList'})
    tags_dl = tag_div.findAll('li')
    for tag_dl in tags_dl:
      if tag_dl.find('strong') == None:
        break
      store = tag_dl.find('strong').text
      store_address = tag_dl.find('em').text.strip().replace("\t","").split("\r\n")[0]
      sido = store_address.split()[0]
      gungu = store_address.split()[1]
      results.append([store]+[sido]+[gungu]+[store_address])

results[0]

import pandas as pd

kychon_tbl = pd.DataFrame(results, columns = ('store', 'sido', 'gungu', 'store_address'))

kychon_tbl.to_csv("kychon.csv", encoding = "cp949", mode = "w", index = True)